### ISSUE TITLE
Can't install g8os-resourcepool using pip

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-rest-api#290]
https://github.com/g8os/resourcepool/tree/master/pyclient#install

**Actual Result**
![screenshot from 2017-05-28 12-20-54](https://cloud.githubusercontent.com/assets/17981089/26527991/5ac493bc-43a0-11e7-8fa3-8f14c935c767.png)

**Comment by grimpy** [comment]
Won't fix under this name, at the end of the relase of alpha3 we will publish it under the new name.
